Repository ISIS3510-S2-G23/flutter_project, pull requests merged in 2025-04, with the labels that each got.

#54 strategy for managing local storage per mobile app
  flutter_app/lib/main.dart
  flutter_app/lib/repositories/posts_repository.dart
  flutter_app/lib/routes/routes.dart
  flutter_app/lib/services/auth_service.dart
  flutter_app/lib/views-viewmodels/account/Edit_Account.dart
  flutter_app/lib/views-viewmodels/account/Help.dart
  flutter_app/lib/views-viewmodels/account/account.dart
  flutter_app/lib/views-viewmodels/home/home.dart
  flutter_app/lib/views-viewmodels/home/splash.dart
  flutter_app/macos/Flutter/GeneratedPluginRegistrant.swift
  flutter_app/pubspec.lock
  flutter_app/pubspec.yaml
  flutter_app/windows/flutter/generated_plugin_registrant.cc
  flutter_app/windows/flutter/generated_plugins.cmake
Labels: code

#55 Refactor Home view to improve caching logic and UI structure; add con…
  flutter_app/lib/views-viewmodels/home/home.dart
Labels: code

#56 Correction sprint 2
  flutter_app/lib/services/chat_gpt_service.dart
  flutter_app/lib/views-viewmodels/auth/login.dart
  flutter_app/lib/views-viewmodels/auth/signup.dart
  flutter_app/lib/views-viewmodels/points/subtabs/challenges.dart
Labels: code

#59 Add PostDatabase and PostModel for local data management; implement P…
  flutter_app/lib/database/post_database.dart
  flutter_app/lib/models/post_model.dart
  flutter_app/lib/repositories/post_repository.dart
  flutter_app/lib/views-viewmodels/home/home.dart
  flutter_app/pubspec.lock
  flutter_app/pubspec.yaml
Labels: code

#61 Which category has the most accumulated upvotes?
  flutter_app/lib/views-viewmodels/home/home.dart
Labels: code

#63 Actualiza la configuración de Firebase Crashlytics para registrar errores fatales; agrega un botón de prueba de excepción en la vista de cuenta; actualiza las versiones de las dependencias de Firebase en pubspec.yaml y pubspec.lock.
  flutter_app/lib/main.dart
  flutter_app/lib/views-viewmodels/account/account.dart
  flutter_app/pubspec.lock
  flutter_app/pubspec.yaml
Labels: bug

#65 Deployment
  flutter_app/android/app/.cxx/Debug/5o72i113/arm64-v8a/configure_fingerprint.bin
  flutter_app/android/app/.cxx/Debug/5o72i113/armeabi-v7a/configure_fingerprint.bin
  flutter_app/android/app/.cxx/Debug/5o72i113/x86/configure_fingerprint.bin
  flutter_app/android/app/.cxx/Debug/5o72i113/x86_64/configure_fingerprint.bin
  flutter_app/lib/database/post_database.dart
  flutter_app/lib/main.dart
  flutter_app/lib/models/post_model.dart
  flutter_app/lib/repositories/post_repository.dart
  flutter_app/lib/repositories/posts_repository.dart
  flutter_app/lib/routes/routes.dart
  flutter_app/lib/services/auth_service.dart
  flutter_app/lib/services/chat_gpt_service.dart
  flutter_app/lib/services/connectivity.dart
  flutter_app/lib/services/location_service.dart
  flutter_app/lib/views-viewmodels/account/Edit_Account.dart
  flutter_app/lib/views-viewmodels/account/Help.dart
  flutter_app/lib/views-viewmodels/account/Log_Out.dart
  flutter_app/lib/views-viewmodels/account/Policy_TermsOfService/PrivacyPolicy.dart
  flutter_app/lib/views-viewmodels/account/Policy_TermsOfService/TermsOfService.dart
  flutter_app/lib/views-viewmodels/account/Setting_Privacy.dart
  flutter_app/lib/views-viewmodels/account/account.dart
  flutter_app/lib/views-viewmodels/auth/login.dart
  flutter_app/lib/views-viewmodels/auth/signup.dart
  flutter_app/lib/views-viewmodels/home/home.dart
  flutter_app/lib/views-viewmodels/home/splash.dart
  flutter_app/lib/views-viewmodels/index_view.dart
  flutter_app/lib/views-viewmodels/map_viewmodel.dart
  flutter_app/lib/views-viewmodels/points/index_points.dart
  flutter_app/lib/views-viewmodels/points/subtabs/challenges.dart
  flutter_app/lib/views-viewmodels/points/subtabs/near_me.dart
  flutter_app/lib/views-viewmodels/points/subtabs/rewards.dart
  flutter_app/macos/Flutter/GeneratedPluginRegistrant.swift
  flutter_app/pubspec.lock
  flutter_app/pubspec.yaml
  flutter_app/windows/flutter/generated_plugin_registrant.cc
  flutter_app/windows/flutter/generated_plugins.cmake
Labels: deployment
