Repository ISIS3510-S2-G23/flutter_project, pull requests merged in 2025-03, with the labels that each got.

#12 Implementar persistencia para el usuario y la adquisición de este en la app
  flutter_app/android/app/google-services.json
  flutter_app/devtools_options.yaml
  flutter_app/lib/routes/routes.dart
  flutter_app/lib/screens/home/home.dart
  flutter_app/lib/services/auth_service.dart
  flutter_app/lib/views/auth/login.dart
  flutter_app/lib/views/auth/signup.dart
  flutter_app/lib/views/auth/signup_success.dart
  flutter_app/lib/views/home/home.dart
  flutter_app/lib/views/notifications/notifications.dart
  flutter_app/lib/views/points/near_me.dart
  flutter_app/lib/views/walkthrough/walkthrough_1.dart
  flutter_app/lib/views/walkthrough/walkthrough_2.dart
  flutter_app/lib/views/walkthrough/walkthrough_3.dart
  flutter_app/macos/Flutter/GeneratedPluginRegistrant.swift
  flutter_app/pubspec.lock
  flutter_app/pubspec.yaml
  flutter_app/test/screens/walkthrough/walkthrough_1_test.dart
  flutter_app/test/screens/walkthrough/walkthrough_2_test.dart
  flutter_app/test/screens/walkthrough/walkthrough_3_test.dart
Labels: code

#10 Añadir indicador de carga en el botón de registro durante el proceso de creación de cuenta
  flutter_app/lib/views/auth/signup.dart
Labels: bug

#23 Añadir Firebase Crashlytics y Firebase Analytics a la aplicación
  flutter_app/android/app/build.gradle
  flutter_app/android/settings.gradle
  flutter_app/lib/main.dart
  flutter_app/macos/Flutter/GeneratedPluginRegistrant.swift
  flutter_app/pubspec.lock
  flutter_app/pubspec.yaml
Labels: code

#27 26 refactor near me tabs
  .vscode/settings.json
  flutter_app/analysis_options.yaml
  flutter_app/lib/main.dart
  flutter_app/lib/views/index_view.dart
  flutter_app/lib/views/points/index_points.dart
  flutter_app/lib/views/points/near_me.dart
  flutter_app/lib/views/points/subtabs/challenges.dart
  flutter_app/lib/views/points/subtabs/near_me.dart
  flutter_app/lib/views/points/subtabs/rewards.dart
  flutter_app/macos/Flutter/GeneratedPluginRegistrant.swift
  flutter_app/pubspec.lock
  flutter_app/pubspec.yaml
Labels: code

#29 14 home page view
  flutter_app/lib/views/home/home.dart
Labels: code

#34 32 create front end for challenges
  flutter_app/lib/views/points/index_points.dart
  flutter_app/lib/views/points/subtabs/challenges.dart
Labels: code, do-not-merge

#35 Ajustar el diseño de la vista de agregar publicación y reducir el tamaño de fuente en la vista de puntos
  flutter_app/lib/views/add_post/add_post.dart
  flutter_app/lib/views/points/index_points.dart
Labels: code

#37 32 create front end for challenges
  flutter_app/lib/views/home/comments_button.dart
  flutter_app/lib/views/home/home.dart
  flutter_app/lib/views/home/upvote_button.dart
Labels: code

#39 Add dotenv support and update configuration files
  .env
  .github/workflows/ci.yml
  flutter_app/.gitignore
  flutter_app/.vscode/settings.json
  flutter_app/android/.gitignore
  flutter_app/lib/main.dart
  flutter_app/lib/services/chat_gpt_service.dart
  flutter_app/lib/views/home/comments_button.dart
  flutter_app/lib/views/home/home.dart
  flutter_app/lib/views/home/upvote_button.dart
  flutter_app/lib/views/points/subtabs/challenges.dart
  flutter_app/pubspec.lock
  flutter_app/pubspec.yaml
Labels: code

#41 Ajustar estilos y colores en botones y diálogos de comentarios
  flutter_app/lib/main.dart
  flutter_app/lib/views/add_post/add_post.dart
  flutter_app/lib/views/home/comments_button.dart
  flutter_app/lib/views/home/home.dart
  flutter_app/lib/views/home/upvote_button.dart
  flutter_app/lib/views/points/index_points.dart
  flutter_app/lib/views/points/subtabs/near_me.dart
  flutter_app/lib/views/points/subtabs/rewards.dart
  flutter_app/lib/views/walkthrough/walkthrough_1.dart
  flutter_app/test/screens/walkthrough/walkthrough_1_test.dart
Labels: code

#43 42 refactor repositories
  flutter_app/lib/repositories/challenges_repository.dart
  flutter_app/lib/repositories/locations_repository.dart
  flutter_app/lib/repositories/posts_repository.dart
  flutter_app/lib/routes/routes.dart
  flutter_app/lib/services/chat_gpt_service.dart
  flutter_app/lib/views-viewmodels/account/account.dart
  flutter_app/lib/views-viewmodels/add_post/add_post.dart
  flutter_app/lib/views-viewmodels/auth/login.dart
  flutter_app/lib/views-viewmodels/auth/signup.dart
  flutter_app/lib/views-viewmodels/auth/signup_success.dart
  flutter_app/lib/views-viewmodels/home/comments_button.dart
  flutter_app/lib/views-viewmodels/home/home.dart
  flutter_app/lib/views-viewmodels/home/upvote_button.dart
  flutter_app/lib/views-viewmodels/index_view.dart
  flutter_app/lib/views-viewmodels/notifications/notifications.dart
  flutter_app/lib/views-viewmodels/points/index_points.dart
  flutter_app/lib/views-viewmodels/points/subtabs/challenges.dart
  flutter_app/lib/views-viewmodels/points/subtabs/near_me.dart
  flutter_app/lib/views-viewmodels/points/subtabs/rewards.dart
  flutter_app/lib/views-viewmodels/walkthrough/walkthrough_1.dart
  flutter_app/lib/views-viewmodels/walkthrough/walkthrough_2.dart
  flutter_app/lib/views-viewmodels/walkthrough/walkthrough_3.dart
  flutter_app/pubspec.lock
  flutter_app/test/screens/walkthrough/walkthrough_1_test.dart
  flutter_app/test/screens/walkthrough/walkthrough_2_test.dart
  flutter_app/test/screens/walkthrough/walkthrough_3_test.dart
Labels: enhancement

#44 Producton deployment - Sprint 2
  flutter_app/lib/repositories/challenges_repository.dart
  flutter_app/lib/repositories/locations_repository.dart
  flutter_app/lib/repositories/posts_repository.dart
  flutter_app/lib/routes/routes.dart
  flutter_app/lib/services/chat_gpt_service.dart
  flutter_app/lib/views-viewmodels/account/account.dart
  flutter_app/lib/views-viewmodels/add_post/add_post.dart
  flutter_app/lib/views-viewmodels/auth/login.dart
  flutter_app/lib/views-viewmodels/auth/signup.dart
  flutter_app/lib/views-viewmodels/auth/signup_success.dart
  flutter_app/lib/views-viewmodels/home/comments_button.dart
  flutter_app/lib/views-viewmodels/home/home.dart
  flutter_app/lib/views-viewmodels/home/upvote_button.dart
  flutter_app/lib/views-viewmodels/index_view.dart
  flutter_app/lib/views-viewmodels/notifications/notifications.dart
  flutter_app/lib/views-viewmodels/points/index_points.dart
  flutter_app/lib/views-viewmodels/points/subtabs/challenges.dart
  flutter_app/lib/views-viewmodels/points/subtabs/near_me.dart
  flutter_app/lib/views-viewmodels/points/subtabs/rewards.dart
  flutter_app/lib/views-viewmodels/walkthrough/walkthrough_1.dart
  flutter_app/lib/views-viewmodels/walkthrough/walkthrough_2.dart
  flutter_app/lib/views-viewmodels/walkthrough/walkthrough_3.dart
  flutter_app/pubspec.lock
  flutter_app/test/screens/walkthrough/walkthrough_1_test.dart
  flutter_app/test/screens/walkthrough/walkthrough_2_test.dart
  flutter_app/test/screens/walkthrough/walkthrough_3_test.dart
Labels: deployment

#46 Eliminar condición redundante en la visualización de recompensas comp…
  flutter_app/lib/views-viewmodels/points/subtabs/rewards.dart
Labels: bug
